# Generated by Django 5.2.6 on 2025-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
